# Generated by Django 2.2.16 on 2020-10-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='description',
        ),
    ]
