# Generated by Django 3.1.3 on 2020-11-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201112_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
