# Generated by Django 3.1.3 on 2020-11-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201109_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_facebook',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_twitter',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
